# Generated by Django 5.2.3 on 2025-08-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_alter_shorturl_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='short_code',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
